### ISSUE TITLE
出问题了老哥

### ISSUE THREAD

**Issue by sxin9** [TravellerXi/SayHiWithWeatherForecast#1]
报错
  File "main.py", line 76, in SendWeatherReportByMsg
    params = [Nickname, thisYear, thisMonth, thisDay, CityChinese, self.Weather, self.Weather_Msg, self.HighTemperature, self.Temperature,\
AttributeError: 'WeatherForecastSender' object has no attribute 'HighTemperature'
按这个下载了直接运行就是这样啊，这是怎么回事

**Comment by TravellerXi** [comment]
Let me check

**Comment by TravellerXi** [comment]
去Request tianqi.com时候，被反爬虫了。

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>403 Forbidden</title></head>
<body>
<h1>403 Forbidden</h1>
<p>You don't have permission to access the URL on this server.<hr/>Powered by Tengine</body>
</html>

我来改下代码，伪装成浏览器访问即可

**Comment by xyu1-sh** [comment]
@jwbcfa 问题应该解决了，请重新下载代码。备注，Python 3.9以上，qcloudsms_py模块有问题，建议使用Python3.8及以下版本。


或者修改qcloudsms_py模块的httpclient.py的第62行，删除' , encoding="utf-8" '

**Comment by sxin9** [comment]
python main.py
failed to init, try again later or check the website
Traceback (most recent call last):
  File "main.py", line 101, in <module>
    thisWeather.SendWeatherReportByMsg("小仙女","徐汇区","测试号码",appid,appkey,template_id)
  File "main.py", line 79, in SendWeatherReportByMsg
    params = [Nickname, thisYear, thisMonth, thisDay, CityChinese, self.Weather, self.Weather_Msg, self.HighTemperature, self.Temperature,\
AttributeError: WeatherForecastSender instance has no attribute 'Weather'
我已开始以为是国外服务器打不开这个天气平台，谁知道换了北京的服务器也是这样子报错。还有第一个错误。appid、appkey啥的上边我看注释那里写过了，就只在上边写好了，但是还是会报错。

**Comment by TravellerXi** [comment]
@jwbcfa 你好，测试了下，徐汇区的城市代码不是"xuhuiqu"而是"xuhui"，我更新了代码里的错误提示。你再更新下代码试试。额外的，如果想获取某个城市某个区的代码，在http://www.tianqi.com/ 搜索并点开后复制URL后的城市代码，复制到代码倒数第二行即可。
